### ISSUE TITLE
诶嘿，发现你的 twitter 了

### ISSUE THREAD

**Issue by fzf404** [widcardw/Shota#2]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/40832831/189798384-fee16243-63dd-471b-9f70-8c502c889ba0.png">

**Comment by widcardw** [comment]
呜呜，tt 上看的都是涩涩

**Comment by fzf404** [comment]
2333我都是两个号，一个主号，一个看nsfw的小号

**Comment by widcardw** [comment]
两个账号该咋搞呀

**Comment by widcardw** [comment]
我只有一个 google 注册的

**Comment by widcardw** [comment]
qq 和 b 站我倒是有两个号，虽然这边两个号都不怎么搞 nsfw 的

**Comment by fzf404** [comment]
emmm，好像之前可以用大陆手机号的时候注册了一个，现在不太清楚了🤪

**Comment by widcardw** [comment]
我当年在 ie 可以用的时候用大陆手机号注册了一个 google 账号

**Comment by widcardw** [comment]
呜呜，现在基本上也没有什么空来画画了，如果早知道，我应该好好卷一卷成绩（同学都太卷了，他们都保研了）。

现在其实找到正太控同好了（

**Comment by fzf404** [comment]
2333，那挺好的，你的关注列表我也都有关注诶。

**Comment by widcardw** [comment]
> 2333，那挺好的，你的关注列表我也都有关注诶。
> […](#)
> 在 2022年9月13日，11:50，widcardw ***@***.***> 写道： ﻿ 呜呜，现在基本上也没有什么空来画画了，如果早知道，我应该好好卷一卷成绩（同学都太卷了，他们都保研了）。 现在其实找到正太控同好了（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

你也是正太控吗（x

**Comment by fzf404** [comment]
是捏XD

**Comment by widcardw** [comment]
超，只有我公开自己是正太控呗

**Comment by fzf404** [comment]
哈哈哈

**Comment by fzf404** [comment]
话说加个qq嘛，441535134
